version: '3.8'
services:
    postgres:
        image: postgres:14.2
        restart: always
        environment: 
          - POSTGRES_USER=minibank
          - POSTGRES_PASSWORD=minibank
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes:
          - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
          # copy the sql script to fill tables
          - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    app:
        build: .
        ports:
          - "8000:8000"
        links:
          - postgres
        environment:
          - PGHOST=postgres
          - PGPORT=5432
          - PGUSER=minibank
          - PGPASS=minibank
          - DBNAME=minibank
